/**
 * Animated Lucide icons (lucide-react-motion). Import icons from here instead of lucide-react.
 */
export {
  Activity,
  Bot,
  Check,
  Check as CheckIcon,
  ChevronDown,
  ChevronDown as ChevronDownIcon,
  ChevronRight,
  ChevronRight as ChevronRightIcon,
  ChevronUp,
  ChevronUp as ChevronUpIcon,
  Circle,
  CircleCheck,
  CircleCheck as CircleCheckIcon,
  Ellipsis as MoreHorizontal,
  FolderOpen,
  Info,
  Info as InfoIcon,
  KeyRound,
  Link2,
  LoaderCircle,
  LoaderCircle as Loader2,
  LoaderCircle as Loader2Icon,
  Menu,
  MessageSquarePlus,
  Mic,
  Monitor,
  OctagonX,
  OctagonX as OctagonXIcon,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Pause,
  Plus,
  Save,
  Search,
  Settings2,
  Sparkles,
  Square,
  Trash2,
  TriangleAlert,
  TriangleAlert as TriangleAlertIcon,
  Wand as Wand2,
  X,
  X as XIcon,
  MotionIconConfig,
} from "lucide-react-motion";
